name       : png++
version    : 0.2.9
release    : 1
source     :
    - http://download.savannah.nongnu.org/releases/pngpp/png++-0.2.9.tar.gz : abbc6a0565122b6c402d61743451830b4faee6ece454601c5711e1c1b4238791
license    : BSD-3-Clause
component  : programming.library
summary    : C++ wrapper for libpng
description: |
    C++ wrapper for libpng
patterns   :
    - /usr/include
builddeps  :
    - pkgconfig(libpng)
build      : |
    %make
install    : |
    %make_install PREFIX="$installdir/usr"
